In [1]:
2*3


6

In [2]:

k=3+4
print(k)



7


In [3]:

(k+1)*(k-1)



48

In [5]:
x=0
(x+1)*(x-1)


-1

In [6]:
h=(k+2)*3+\
3+(k+7)
print(h)

44


In [7]:
%reset
x=1
y=2
z=3
t=4
%whos
del(x)
%whos

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


Variable   Type    Data/Info
----------------------------
t          int     4
x          int     1
y          int     2
z          int     3
Variable   Type    Data/Info
----------------------------
t          int     4
y          int     2
z          int     3


$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$


In [8]:
import numpy as np
B = np.array([1, 3, -1])
print(B)


[ 1  3 -1]


In [9]:
import numpy as np
A = np.array( [ [1, 2, 3, 4], [0, 1, 3, 2] ] ) 
print(A) 

[[1 2 3 4]
 [0 1 3 2]]


In [10]:
v = np.arange(1,8,2) 
print (v)


[1 3 5 7]


In [11]:
import numpy as np
A = np.arange(4)
5
print('A =', A)
B = np.arange(12).reshape(2, 6)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


$\begin{bmatrix} 1 & 2 & 1 & 1 \\ 3 & 0 & 1 & 1 \\ 0 & 2 & 4 & 1 \end{bmatrix}$

In [26]:
import numpy as np
A = np.array( [ [1, 2, 1, 1],[3 , 0, 1, 1], [0,2,4,1]] ) 
A[2,3]=-A[2,3]
A[0,2]=A[0,2]-4
A[0,:]=A[0,:]*3
A[:,1]=A[:,1]*2
print(A)

[[ 3 12 -9  3]
 [ 3  0  1  1]
 [ 0  4  4 -1]]


In [44]:
v = np.arange(1,6,1) 
print (v)
v1=np.arange(1,8,1)
print(v1)
v2=np.arange(1,10,1)
print(v2)


[1 2 3 4 5]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]


In [50]:
B = np.arange(1,10,1).reshape(9,1)
print(B)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [49]:


B1 = np.arange(1,6,1).reshape(5,1)
print(B1)


[[1]
 [2]
 [3]
 [4]
 [5]]


In [48]:

B2 = np.arange(1,3,1).reshape(2,1)
print(B2)

[[1]
 [2]]


In [51]:
import numpy as np
import numpy.matlib
X = np.matlib.ones((2,3))
Y = np.matlib.matrix('1, 2, 3; 3, 2, 1')
print(X)
print(Y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [3 2 1]]


In [72]:
import numpy as np
A = np.matlib.matrix('1, 2, 3; 4, 5, 6')
B = np.matlib.matrix('1, -2, 1; -2, 3, 4')
c=2
D = np.matlib.ones((2,3))
E = np.matlib.eye(3)

print(A)
print(B)
print(D)
print(E)
print(A+B)
print(A+E)
print(A*c)
B1 = B.transpose()
print(A*B1)

[[1 2 3]
 [4 5 6]]
[[ 1 -2  1]
 [-2  3  4]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 2  0  4]
 [ 2  8 10]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
разная размерность ^  
                   !
