In [1]:
import numpy as np
from sympy import *


In [2]:
#Упражнение 2.1

In [29]:
a,b,x=symbols('a b x')
v=Matrix([[-1,4],[-5,2]])
v1=Matrix([[a+b,a-b],[a+b,a-b]])
v2=Matrix([[x,x+1],[-4,x+1]])

detV = (v[0,0] * v[1, 1]) - (v[0, 1] * v[1, 0])
detV1 = (v1[0,0] * v1[1, 1]) - (v1[0, 1] * v1[1, 0])
detV2= (v2[0,0] * v2[1, 1]) - (v2[0, 1] * v2[1, 0])
print(detV)
print(detV1)
print(detV2)




18
0
x*(x + 1) + 4*x + 4
Matrix([[-1, 4], [-5, 2]])


In [4]:
det(v)

18

In [5]:

det(v1)

0

In [6]:
det(v2)

x**2 + 5*x + 4

In [7]:
#Упражнение 2.2


In [8]:
a,b,x,c=symbols('a b x c')
p=Matrix([[1,2,3],[4,5,6],[7,8,1]])
p1=Matrix([[3,4,-5],[8,7,-2],[2,-1,8]])
p2=Matrix([[a+x,x,x],[x,b+x,x],[x,x,c+x]])
p3=Matrix([[sin(a),cos(a),1],[sin(b),cos(b),1],[sin(c),cos(c),1]])
det(p)


24

In [9]:

det(p1)


0

In [10]:

det(p2)


a*b*c + a*b*x + a*c*x + b*c*x

In [11]:

det(p3)

sin(a)*cos(b) - sin(a)*cos(c) - sin(b)*cos(a) + sin(b)*cos(c) + sin(c)*cos(a) - sin(c)*cos(b)

In [12]:
#Упражнение 2.3

In [13]:
A = np.matrix('3 -5 ; 2 7')
print(A)
B = np.matrix('13 ; 81')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
print(X_m)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
x1 = np.linalg.det(X_m) / A_det
x2 = np.linalg.det(Y_m) / A_det
print(x1)
print(x2)
#Сделаем проверку
x=np.matrix([[x1],[x2]])
print(A*x)
print(B)


[[ 3 -5]
 [ 2  7]]
[[13]
 [81]]
31.0
[[ 3 -5]
 [ 2  7]]
[[13 -5]
 [81  7]]
[[ 3 13]
 [ 2 81]]
16.000000000000007
7.000000000000001
[[13.]
 [81.]]
[[13]
 [81]]


In [14]:
A = np.matrix('3 -4 ; -6 8')
print(A)
B = np.matrix('-6 ; 12')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
print(X_m)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
x1 = np.linalg.det(X_m) / A_det
x2 = np.linalg.det(Y_m) / A_det
print(x1)
print(x2)
#Определитель равен 0 -> решений нет

[[ 3 -4]
 [-6  8]]
[[-6]
 [12]]
0.0
[[ 3 -4]
 [-6  8]]
[[-6 -4]
 [12  8]]
[[ 3 -6]
 [-6 12]]
nan
nan


C:\Users\вольвокс\AppData\Local\Temp\ipykernel_15076\3752082692.py:14: RuntimeWarning: invalid value encountered in scalar divide
  x1 = np.linalg.det(X_m) / A_det
C:\Users\вольвокс\AppData\Local\Temp\ipykernel_15076\3752082692.py:15: RuntimeWarning: invalid value encountered in scalar divide
  x2 = np.linalg.det(Y_m) / A_det


In [15]:
A = np.matrix('7 2 3; 5 -3 2; 10 -11 5')
print(A)
B = np.matrix('15; 15; 36')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
print(X_m)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
Z_m = np.matrix(A)
Z_m[:, 2] = B
print(Z_m)
x1 = np.linalg.det(X_m) / A_det
x2 = np.linalg.det(Y_m) / A_det
x3 = np.linalg.det(Z_m) / A_det
print(x1)
print(x2)
print(x3)
#Сделаем проверку
x=np.matrix([[x1],[x2],[x3]])
print(A*x)
print(B)


[[  7   2   3]
 [  5  -3   2]
 [ 10 -11   5]]
[[15]
 [15]
 [36]]
-36.0
[[  7   2   3]
 [  5  -3   2]
 [ 10 -11   5]]
[[ 15   2   3]
 [ 15  -3   2]
 [ 36 -11   5]]
[[ 7 15  3]
 [ 5 15  2]
 [10 36  5]]
[[  7   2  15]
 [  5  -3  15]
 [ 10 -11  36]]
2.0
-1.0000000000000009
0.9999999999999964
[[15.]
 [15.]
 [36.]]
[[15]
 [15]
 [36]]


In [18]:
A = np.matrix('2 1 0; 1 0 3; 0 5 -1')
print(A)
B = np.matrix('5; 16; 10')
print(B)
A_det = np.linalg.det(A)
print(A_det)
X_m = np.matrix(A)
print(X_m)
X_m[:, 0] = B
print(X_m)
Y_m = np.matrix(A)
Y_m[:, 1] = B
print(Y_m)
Z_m = np.matrix(A)
Z_m[:, 2] = B
print(Z_m)
x1 = np.linalg.det(X_m) / A_det
x2 = np.linalg.det(Y_m) / A_det
x3 = np.linalg.det(Z_m) / A_det
print(x1)
print(x2)
print(x3)
#Сделаем проверку
x=np.matrix([[x1],[x2],[x3]])
print(A*x)
print(B)


[[ 2  1  0]
 [ 1  0  3]
 [ 0  5 -1]]
[[ 5]
 [16]
 [10]]
-28.99999999999999
[[ 2  1  0]
 [ 1  0  3]
 [ 0  5 -1]]
[[ 5  1  0]
 [16  0  3]
 [10  5 -1]]
[[ 2  5  0]
 [ 1 16  3]
 [ 0 10 -1]]
[[ 2  1  5]
 [ 1  0 16]
 [ 0  5 10]]
1.0
3.000000000000001
5.000000000000001
[[ 5.]
 [16.]
 [10.]]
[[ 5]
 [16]
 [10]]


#Упражнение 2.4

In [50]:
from sympy import *

A = Matrix([[3,-5],[2,7]])
print(A, type (A))
B = Matrix([[13,81]])
print(B)
A_det = det(A)
print(A_det)
X_m = Matrix(A)
print(X_m)
X_m[:, 0] = [[13], [81]]
print(X_m)
Y_m = Matrix(A)
Y_m[:, 1] = [[13], [81]]
print(Y_m)
x1 = det(X_m) / A_det
x2 = det(Y_m) / A_det
print(x1)
print(x2)
#Сделаем проверку
x=Matrix([[x1],[x2]])
print(A*x)
print(B)


Matrix([[3, -5], [2, 7]]) <class 'sympy.matrices.dense.MutableDenseMatrix'>
Matrix([[13, 81]])
31
Matrix([[3, -5], [2, 7]])
Matrix([[13, -5], [81, 7]])
Matrix([[3, 13], [2, 81]])
16
7
Matrix([[13], [81]])
Matrix([[13, 81]])


In [48]:
A = Matrix([[7,2,3],[5,-3,2],[10,-11,5]])
print(A)
B = Matrix([[15], [15], [36]])
print(B)
A_det = det(A)
print(A_det)
X_m = Matrix(A)
print(X_m)
X_m[:, 0] = [[15], [15], [36]]
print(X_m)
Y_m = Matrix(A)
Y_m[:, 1] = [[15], [15], [36]]
print(Y_m)
Z_m = Matrix(A)
Z_m[:, 2] = [[15], [15], [36]]
print(Z_m)
x1 = det(X_m) / A_det
x2 = det(Y_m) / A_det
x3 = det(Z_m) / A_det
print(x1)
print(x2)
print(x3)
#Сделаем проверку
x=Matrix([[x1],[x2],[x3]])
print(A*x)
print(B)

Matrix([[7, 2, 3], [5, -3, 2], [10, -11, 5]])
Matrix([[15], [15], [36]])
-36
Matrix([[7, 2, 3], [5, -3, 2], [10, -11, 5]])
Matrix([[15, 2, 3], [15, -3, 2], [36, -11, 5]])
Matrix([[7, 15, 3], [5, 15, 2], [10, 36, 5]])
Matrix([[7, 2, 15], [5, -3, 15], [10, -11, 36]])
2
-1
1
Matrix([[15], [15], [36]])
Matrix([[15], [15], [36]])


In [ ]:
#Упражнение 2.5

In [52]:
A = np.matrix('3 -5; 2 7')
B = np.matrix('13 ; 81')
print(A)
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
X

[[ 3 -5]
 [ 2  7]]
[[13]
 [81]]
[[ 0.22580645  0.16129032]
 [-0.06451613  0.09677419]]


matrix([[16.],
        [ 7.]])

In [53]:
A = np.matrix('3 -4; -6 8')
B = np.matrix('-6 ; 12')
print(A)
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
X
#Решений нет

[[ 3 -4]
 [-6  8]]
[[-6]
 [12]]


LinAlgError: Singular matrix

In [54]:
A = np.matrix('7 2 3; 5 -3 2; 10 -11 5')
B = np.matrix('15 ; 15 ; 36')
print(A)
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
X

[[  7   2   3]
 [  5  -3   2]
 [ 10 -11   5]]
[[15]
 [15]
 [36]]
[[-0.19444444  1.19444444 -0.36111111]
 [ 0.13888889 -0.13888889 -0.02777778]
 [ 0.69444444 -2.69444444  0.86111111]]


matrix([[ 2.],
        [-1.],
        [ 1.]])

In [55]:
A = np.matrix('2 1 0; 1 0 3; 0 5 -1')
B = np.matrix('5 ; 16; 10')
print(A)
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
X

[[ 2  1  0]
 [ 1  0  3]
 [ 0  5 -1]]
[[ 5]
 [16]
 [10]]
[[ 0.51724138 -0.03448276 -0.10344828]
 [-0.03448276  0.06896552  0.20689655]
 [-0.17241379  0.34482759  0.03448276]]


matrix([[1.],
        [3.],
        [5.]])